"""session refrash key

Revision ID: 1b77727e4b3d
Revises: 83dae6d115fb
Create Date: 2026-03-16 10:51:14.978739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b77727e4b3d'
down_revision: Union[str, None] = '83dae6d115fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshdatas', sa.Column('session', sa.String(length=100), nullable=True))
    op.create_foreign_key('fk_refreshdatas_sessions_id_session', 'refreshdatas', 'sessions', ['session'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_refreshdatas_sessions_id_session', 'refreshdatas', type_='foreignkey')
    op.drop_column('refreshdatas', 'session')
    # ### end Alembic commands ###
