"""session auth code

Revision ID: 8e8cffdbecde
Revises: 1b77727e4b3d
Create Date: 2026-03-16 22:24:40.203528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8cffdbecde'
down_revision: Union[str, None] = '1b77727e4b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorizencodes', sa.Column('session', sa.String(length=100), nullable=True))
    op.create_foreign_key('fk_authorizencodes_sessions_id_session', 'authorizencodes', 'sessions', ['session'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_authorizencodes_sessions_id_session', 'authorizencodes', type_='foreignkey')
    op.drop_column('authorizencodes', 'session')
    # ### end Alembic commands ###
