"""token size

Revision ID: 943ae97bb2c4
Revises: 8e8cffdbecde
Create Date: 2026-03-17 10:51:25.651742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '943ae97bb2c4'
down_revision: Union[str, None] = '8e8cffdbecde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorizencodes', 'code',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('refreshdatas', 'token',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refreshdatas', 'token',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('authorizencodes', 'code',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
