"""session refrash

Revision ID: ac4afe9f307a
Revises: 8c9c9e3190ca
Create Date: 2026-03-16 10:35:47.076426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac4afe9f307a'
down_revision: Union[str, None] = '8c9c9e3190ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshdatas',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('client', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['clients.id'], name='fk_refreshdatas_clients_id_client', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_refreshdatas_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('refreshs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshs',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('client', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['clients.id'], name='fk_refreshs_clients_id_client', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_refreshs_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('refreshdatas')
    # ### end Alembic commands ###
